providers:
  - provider : GitHub
    url : https://api.github.com/user/repos
    authHeaderName : Authorization
    authHaederValue : token 07c8fd957bd4578a31545c4a150e873642d68546
    idKey : id
    nameKey : name
    ownerKey : owner
    useidKey : login
    htmlUrlKey : html_url
    sshUrlKey  : ssh_url
  - provider : GitLab
    url : https://gitlab.com/api/v4/users/manadeepjadhav/projects
    authHeaderName : Authorization
    authHaederValue : Bearer gEm9nLwWctdmcyN77EQK
    idKey : id
    nameKey : name
    ownerKey : owner
    useidKey : name
    htmlUrlKey : http_url_to_repo
    sshUrlKey  : ssh_url_to_repo